### ISSUE TITLE
Add support for games other than Sonic 3

### ISSUE THREAD

**Issue by Sophira** [Sophira/LiveSplit.RealTimeMinusBonuses#4]
The plugin currently supports only Sonic 3 and games based on that engine. This should be expanded - preferably allowing the user to specify their own timings, too.

**Comment by CTFSoph** [comment]
I've added this locally, but will wait on a public release until it's been tested a little more as there are still plenty of opportunities for bugs to arise.

**Comment by Sophira** [comment]
I've added this locally, but will wait on a public release until it's been tested a little more as there are still plenty of opportunities for bugs to arise.

**Comment by Sophira** [comment]
This is now officially fixed as of release 0.7!
